image: node:16.14.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm install
    - npm run bp
  artifacts:
    paths:
      - dist
  only:
    - main
