image: trion/ng-cli-karma

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - main
  script:
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng build